### PR TITLE
Add NI, Wales, scotland and Sahrawi

### PR DESCRIPTION
**Pull request by stephenkerrhs**
Add a few more countries.

### CODE REVIEW

**Comment by Intrepidd** [comment]
Cool, thanks !

Do you need a release to rubygems ?

**Comment by stephenkerrhs** [comment]
@Intrepidd Yeah sure why not.

**Comment by Intrepidd** [comment]
Done

**Comment by stephenkerrhs** [comment]
Thank you Adrien :)

**Pull request merged**
